### STAGE 1: Build ###
FROM node:12.22-alpine3.14 AS build
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run post-install-ibm-plex
RUN > ./src/environments/environment.prod.ts
RUN > ./src/environments/environment.ts
RUN npm run build-production
### STAGE 2: Run ####
FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
# COPY --from=build /usr/src/app/DomainVerification.html /usr/share/nginx/html
EXPOSE 80
RUN echo "Completed docker build!"

