spring:
  profiles:
    active: local
  main:
    banner-mode: "off"
  batch:
    initialize-schema: always


springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
    disable-swagger-default-url: true
