FROM python:3.8-slim

ENV PYTHONUNBUFFERED True

WORKDIR /app
RUN chgrp -R 0 /app && chmod -R g=u /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD exec gunicorn --bind :8080 --workers 1 --threads 8 --timeout 0 app:app
